---

language: bash
sudo: required

services:
  - docker

before_install:
  - sudo docker pull centos
  - sudo docker build --no-cache --rm --file=travis/Dockerfile.centos --tag=testingauter:centos travis

script:
  - container_id=$(mktemp)

  - sudo docker run --detach --interactive --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible testingauter:centos > "${container_id}"

  - sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/auter_manager.yml --syntax-check -i /etc/ansible/travis/test.inv -l localhost

  - sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/auter_manager.yml -e "ini_csv_file=travis/test_auter_config.csv ini_reboot=no" -i /etc/ansible/travis/test.inv -l localhost

  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/auter_manager.yml -e "ini_csv_file=/etc/ansible/travis/test_auter_config.csv ini_reboot=no" -i /etc/ansible/travis/test.inv -l localhost
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - sudo docker exec "$(cat ${container_id})" sh -c "/usr/bin/egrep -v '^$|^#' /etc/auter/auter.conf /etc/cron.d/auter | tee /etc/ansible/travis/config_result"
  - sudo docker exec "$(cat ${container_id})" sh -c "/usr/bin/auter --status | tee -a /etc/ansible/travis/config_result"

  #- sudo docker exec "$(cat ${container_id})" /usr/bin/md5sum /etc/ansible/travis/config_result
  - sudo docker exec "$(cat ${container_id})" /usr/bin/md5sum -c /etc/ansible/travis/config_result.md5

  - sudo docker rm -f "$(cat ${container_id})"

...
