---

language: bash
sudo: required

services:
  - docker

before_install:
  - 'sudo docker pull centos'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.centos --tag=testingauter:centos travis'

script:
  - container_id=$(mktemp)

  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible testingauter:centos > "${container_id}"'

  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/auter_manager.yml --syntax-check -i /etc/ansible/travis/test.inv -l localhost'

  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/auter_manager.yml -e "ini_csv_file=travis/test_auter_config.csv ini_reboot=no" -i /etc/ansible/travis/test.inv -l localhost'

  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/auter_manager.yml -e "ini_csv_file=/etc/ansible/travis/test_auter_config.csv ini_reboot=no" -i /etc/ansible/travis/test.inv -l localhost
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - 'sudo docker rm -f "$(cat ${container_id})"'

...
