---

# This is the main auter-installer playbook.
# It includes all tasks to install auter and other related tools such as:
# - nimbus monitoring setup for auter
# - installation of configsnap, used to save state of server before and after reboot
#
# We also call the playbook auter_scheduler that sets up the cron lines for prep
# and apply in /etc/cron.d/auter
#
# All configuration should be present in a csv file matching 
# auter_config_template.csv format/definition.

- hosts: all
  tags: install
  become: True
  gather_facts: False
  vars_prompt:
    - name: "ini_csv_file"
      prompt: "Enter config file (defaults to ./auter_config.csv)"
      default: "./auter_config.csv"
      private: no
    - name: "ini_reboot"
      prompt: "Should we systematically reboot on 'auter --apply'? (This will trigger reboot and associated scritps even if there are no available updates) <yes|no>"
      default: False
      private: no

  # Need to do this to get variables usable in both playbooks
  pre_tasks:
    - name: set variable csv_file for all plays
      tags: schedule
      set_fact:
        csv_file: '{{ ini_csv_file }}'
    - name: set variable reboot for all plays
      tags: schedule
      set_fact:
        reboot: '{{ ini_reboot }}'

  roles:
    - auter_installer
    - auter_scheduler
